/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(symbolmapper_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5c5ce9c5ae6869c973852c7a40ae181d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dvbc/symbolmapper_bb.h>
// pydoc.h is automatically generated in the build directory
#include <symbolmapper_bb_pydoc.h>

void bind_symbolmapper_bb(py::module& m)
{

    using symbolmapper_bb    = ::gr::dvbc::symbolmapper_bb;


    py::class_<symbolmapper_bb, gr::block, gr::basic_block,
        std::shared_ptr<symbolmapper_bb>>(m, "symbolmapper_bb", D(symbolmapper_bb))

        .def(py::init(&symbolmapper_bb::make),
           py::arg("constellation"),
           D(symbolmapper_bb,make)
        )
        



        ;




}








